### ISSUE TITLE
Image url path

### ISSUE THREAD

**Issue by sparklingsparklers** [hans2103/Sitemap#1]
Can someone help me with this?

On my sitemap the image url's are just listed as "http://www.myurl.com/media/catalog/product"

If anyone can help me with this, it would be much appreciated!

Thanks!

**Comment by hans2103** [comment]
What do expect them to be?
/media/catalog/product is the location of the product images.

**Comment by sparklingsparklers** [comment]
Ohhhhh, I thought it made a link directly to the actual image. Sorry for my misunderstanding! 

Alan Wilson

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.
